name                                            = CodelyTvJavaDddExample
property.filename                               = logs
appenders                                       = console, file

status                                          = warn

appender.console.name                           = CONSOLE
appender.console.type                           = CONSOLE
appender.console.target                         = SYSTEM_OUT

appender.console.layout.type = JsonTemplateLayout
appender.console.layout.eventTemplateUri      = classpath:LogstashJsonEventLayoutV1.json
appender.console.layout.stackTraceEnabled     = true

appender.file.type                              = File
appender.file.name                              = LOGFILE
appender.file.fileName                          = var/log/java-ddd-example.log
appender.file.layout.type = JsonTemplateLayout
appender.file.layout.eventTemplateUri         = classpath:LogstashJsonEventLayoutV1.json
appender.file.layout.stackTraceEnabled        = true

loggers                                         = file
logger.file.name                                = tv.codely.java_ddd_example
logger.file.level                               = info
logger.file.appenderRefs                        = file
logger.file.appenderRef.file.ref                = LOGFILE

rootLogger.level                                = info
rootLogger.appenderRefs                         = stdout
rootLogger.appenderRef.stdout.ref               = CONSOLE
